### ISSUE TITLE
jointour command

### ISSUE THREAD

**Issue by panpawn** [Ecuacion/Pokemon-Showdown-Node-Bot#20]
It stopped working, I think due to a recent thing with a change in tournaments?

It says it can't play this tier / doesn't have a team for this tier but it worked before for those tiers.

**Comment by Ecuacion** [comment]
It's working for me. I tested in localhost: when it's a random format, the bot joins the tour; when it a team-required format, the bot joins only if it have a team, else it send the error message. Also my bots in main server work properly with tournaments joining.

Is your Bot Updated? [Pokemon showdown format system changed](https://github.com/Zarel/Pokemon-Showdown/commit/3aefdbf7e05153f585e0d9a9832cc43be6f98678) some weeks ago and [i updated the bot to support it](https://github.com/Ecuacion/Pokemon-Showdown-Node-Bot/commit/4760e1e345f47d4ea71edc69a8338548cc1b46b7), probably this is the problem.
