### ISSUE TITLE
Problems with Games + Suggestion

### ISSUE THREAD

**Issue by Freigeist** [Ecuacion/Pokemon-Showdown-Node-Bot#24]
The anagrams game accepts the same answer multiple times, even from the same user. Answering multiple time will award one point each time. Should be fixed.

Suggestion for another game: kunc. kunc is a game in which 4 moves are shown you must guess which pokemon is searched for. For an example see [sparkychild's ChuChuBoTTT] (https://github.com/sparkychild/ChuChuBoTTT/blob/master/commands/kunc.js).

Edit: Another suggestion: Use the translation feature to provide translated names for pokeanagrams or pokehangman.

**Comment by Ecuacion** [comment]
Fixed Anagrams bug in 203c6a9db60fca1f3b5243af4862aae6bc34ac56
idk why but I forgot checking the game status and changing it when a word is guessed.

Also, thanks for the suggestions. I had planned add trivia and kunc games anyway. Using the translation feature for objects, items, abilities and natures in Poke-Hangman and Poke-Anagrams sounds a great idea.

**Comment by Ecuacion** [comment]
Kunc game implemented in e5e936e87cb3abd71ab7541c798243a286388265
Translation feature for Poke-Hangman and Poke-Anagrams implemented in 2dbbc5617498f8af3ce9ccbc0072a2fb714bf82a
