### ISSUE TITLE
Multiple Answers

### ISSUE THREAD

**Issue by Flareninja** [Ecuacion/Pokemon-Showdown-Node-Bot#25]
Hi, how can I add multiple answers in trivia?

**Comment by Ecuacion** [comment]
https://github.com/Ecuacion/Pokemon-Showdown-Node-Bot/blob/master/data/trivia-data-example.js

You can add multiple answers in trivia with a String array, for example:

```js
{q: "Question", a: ["Answer1", "Answer2", "Answer3"]}
```

**Comment by Flareninja** [comment]
Thanks
