### ISSUE TITLE
[Suggestion] Say Good Luck and Have Fun on start of battle

### ISSUE THREAD

**Issue by DaniellMesquita** [Ecuacion/Pokemon-Showdown-Node-Bot#31]
Say Good Luck and Have Fun or gl n' hf on start of battle.

**Comment by Ecuacion** [comment]
You can configure it.
See https://github.com/Ecuacion/Pokemon-Showdown-Node-Bot/blob/master/config-example.js#L254-L256

**Comment by DaniellMesquita** [comment]
Will be nice if this occur automatically before battles like the "GG" phrases after the battles, but ok. I'll configure it.

**Comment by Ecuacion** [comment]
It occurs automatically. The difference between the lose / win messages is that they are configured by default, but you can change them.

Anyway I'll change the default config to enable the battle welcome messages by default.

**Comment by Ecuacion** [comment]
Done in 2f15cc535244205d3ec892d209e281a76b7c388e
