### ISSUE TITLE
Protocol for getserver.js must be updated

### ISSUE THREAD

**Issue by TruBlaze** [Ecuacion/Pokemon-Showdown-Node-Bot#32]
When I do "node getserver.js" and enter the server I want it to connect to, it's giving an undefined error.

----------------------------------------------------
Configure your Pokemon Showdown Bot    
----------------------------------------------------

Client url for server (example.psim.us): origin.psim.us
Getting data for origin.psim.us...
This may take some time, depending on Showdown's speed.

server: undefined
port: undefined
serverid: undefined

Do you want to write this in config.js? (yes, no):

**Comment by Ecuacion** [comment]
Maybe the showdown protocol for servers changed. i'll check it

**Comment by Ecuacion** [comment]
Fixed in 6e527dc449b878556163ea69cee5e1ab96d49a7b. Can you confirm it?

**Comment by TruBlaze** [comment]
Correct.

-------------------------------------------
    Configure your Pokemon Showdown Bot    
-------------------------------------------

Client url for server (example.psim.us): origin.psim.us
Getting data for origin.psim.us...
This may take some time, depending on Showdown's speed.

server: 158.69.205.118
port: 7000
serverid: origin
