### ISSUE TITLE
Enable leaderboards and add old gen teams

### ISSUE THREAD

**Issue by Flareninja** [Ecuacion/Pokemon-Showdown-Node-Bot#33]
Hi, how can I enable leaderboard in a room?

And how I give rby/gsc teams?It tells me "Error: Invalid team data"

**Comment by Ecuacion** [comment]
You can enable it in the config, see https://github.com/Ecuacion/Pokemon-Showdown-Node-Bot/blob/master/config-example.js#L302-L311

Add in `config.js` something like this and replace 'tournaments' for the corresponding room id.

```js
exports.leaderboards = {};

exports.leaderboards['tournaments'] = {
	winnerPoints: 5,
	finalistPoints: 3,
	semiFinalistPoints: 1,
	battlePoints: 0
};
```
Also, i'll check the bug with rby/gsc teams

**Comment by Ecuacion** [comment]
Bug fixed in 912c90e3cd396985a3d2381a0259f65dc1eebd90

**Comment by Flareninja** [comment]
Thanks

**Comment by Flareninja** [comment]
I noticed that when there is a suspect the teams given before the suspect don't work, what can I do?

**Comment by Ecuacion** [comment]
Do you mean teams with Gothitelle shadow tag for example? You can simply delete the teams no longer valid for the tier with `team delete, [team-id]`. You can view all teams ids with `teamslist`

https://github.com/Ecuacion/Pokemon-Showdown-Node-Bot/tree/master/commands#battle

**Comment by Flareninja** [comment]
I mean that when there is in progress a suspect test, the tier changes name and the teams given before don't work(the bot tells that it hasn't teams in that tier)
(Sorry for my english)

**Comment by Ecuacion** [comment]
This behavior is intentional. That's because OU and OU (Suspect test) are different formats with maybe different rules. So you must add new teams for OU (Suspect test), because OU teams can be invalid.

**Comment by Flareninja** [comment]
Ok, thanks
