### ISSUE TITLE
Won't Join With Username and Password in exports

### ISSUE THREAD

**Issue by Hacking3DS** [Ecuacion/Pokemon-Showdown-Node-Bot#49]
Bot won't join to a server if the bot has a password
It says it connects but never joins
I've tried this many times and it doesn't work...

**Comment by Salamencizer** [comment]
Yeah, I had that problem before I switched to Digital ocean from cloud9.
Don't use c9. It won't work.

**Comment by Salamencizer** [comment]
It wont work because you're using Cloud9. Use Google Could, Digital Ocean, or just run it locally.

**Comment by Hacking3DS** [comment]
but those aren't free and I'm broke af

**Comment by Salamencizer** [comment]
Then run it locally :-/ 
Just use a PC, connect it to internet, run the bot, and never turn it off

**Comment by Salamencizer** [comment]
Also, whatever bot you run(foxie, chuchu, ecuacion) nothing would allow it to login if you use c9.

**Comment by Hacking3DS** [comment]
okay thanks

**Comment by Salamencizer** [comment]
Oh wait, just thought of something. You can use Digital Ocean (for free) by getting [Github Student Pack](education.github.com/pack), or use[my link](https://m.do.co/c/64afb4e7eb2f) to get $10 credit.
