### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by panpawn** [Ecuacion/Pokemon-Showdown-Node-Bot#5]
I know that this is really the wrong place to post this, but I've sent you an email and haven't gotten a reply and know no other way to contact you.

I'm using your bot on my server and I have a lot of cool and interesting suggestions for you, and I would also like to show you some stuff I've been doing with it.  If you could come on my server sometime for me to show you / talk to you, that'd be really cool.  (Server is Gold)

Thanks in advanced and for developing a great bot n_n

**Comment by Ecuacion** [comment]
First, thanks for offer help and sorry for not answering, but I tend to get not really many important mails and i have a lot of disorder with notifications and spam so i did not see the mail. Anyway, If you have a suggestion or the bot has a bug you can open an issue or send a pull request.

I'll visit the server when I can. Also you can contact me via [Smogon](http://www.smogon.com/forums/conversations/add?to=Ecuacion) or when I am on Pokemon Showdown I usually frecuent [Español room](http://play.pokemonshowdown.com/espaol)
